version: '3'

services:
  # Load Balancer - Nginx
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    user: root
    depends_on:
      - django
    networks:
      - techblog_network
    restart: always
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/conf.d
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - NGINX_HOST=localhost
      - DOMAIN=${DOMAIN:-example.com}
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Security: Using official image, regularly update to patch vulnerabilities.
    # Enforces HTTPS and adds security headers.

  # Web Application - Django with Gunicorn
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: gunicorn techblog_cms.wsgi:application --bind 0.0.0.0:8000 --error-logfile - --capture-output --log-level debug
    volumes:
      - .:/app
      - logs:/app/logs
    expose:
      - 8000
    environment:
      SECRET_KEY: ${SECRET_KEY:-somesecretkey}  # Replace with a strong secret key
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1,blog.iohub.link}
      DATABASE_URL: postgres://${POSTGRES_USER:-techblog}:${POSTGRES_PASSWORD:-techblogpass}@db:5432/${POSTGRES_DB:-techblogdb}
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: techblog_cms.settings
      PYTHONPATH: /app
    depends_on:
      - db
      - redis
    networks:
      - techblog_network
    restart: always
    # Security: Runs the application as a non-root user.
    # Environment variables for sensitive settings.

  # Database - PostgreSQL
  db:
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-techblog}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-techblogpass}
      POSTGRES_DB: ${POSTGRES_DB:-techblogdb}
    networks:
      - techblog_network
    restart: always
    # Security: Uses a specific PostgreSQL version.
    # Environment variables for credentials.

  # Caching - Redis
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass your_redis_password # Set a password
    ports:
      - "6379:6379"
    networks:
      - techblog_network
    restart: always
    # Security: Requires a password for authentication.
    # Consider network restrictions for enhanced security.

  # Static Files Server
  static:
    image: nginx:alpine
    volumes:
      - static_volume:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - techblog_network
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:rw
      - certbot_etc:/etc/letsencrypt:rw
      - certbot_var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    user: root
    entrypoint: "/bin/sh"
    command: >
      -c 'trap exit TERM; while :; do 
      certbot renew --webroot -w /var/www/certbot --deploy-hook "cp -fL /etc/letsencrypt/live/${DOMAIN:-example.com}/* /etc/nginx/ssl/ && chmod 644 /etc/nginx/ssl/*.pem" --quiet && 
      sleep 12h & wait $${!}; 
      done'
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN:-example.com}
      - EMAIL=${EMAIL:-admin@example.com}

networks:
  techblog_network:
    driver: bridge

volumes:
  db_data:
  static_volume:
  logs:
    driver: local
  media_volume:
    driver: local
  certbot_etc:
  certbot_var:
  webroot:
