# Generated by Django 4.2.10 on 2026-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techblog_cms', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published', '-created_at'], name='article_pub_created_idx'),
        ),
    ]
